
CREATE TABLE Department
(
    id int PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(200) NOT NULL
);

CREATE TABLE Employee
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employeeNumber BIGINT NOT NULL,
    accountNumber int NOT NULL,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    age INTEGER NOT NULL DEFAULT 18,
    department int,
    address varchar(100),
    FOREIGN KEY (department) REFERENCES Department(id)
);
