
CREATE TABLE Department
(
    id int PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(200) NOT NULL
);

CREATE TABLE Employee
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number BIGINT NOT NULL,
    account_number int NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    age INTEGER NOT NULL DEFAULT 18,
    department varchar(20),
    FOREIGN KEY (department) REFERENCES Department(id)
);
